import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        {children}
        <footer className="lg:ms-14">
        <div className="text-lg">By Jinwang Wu</div>
        <div className="text-lg">wujw2013@gmail.com</div>
        <div className="mt-4">Frontend source code: <a href="https://github.com/wujinwang/vehicle-dashboard-react" className="text-red-600">React/Next/Tailwind</a></div>
        <div className="mt-1">Backend source code: <a href="https://github.com/wujinwang/vehicle-dashboard-java" className="text-red-600">Java/Spring boot/MySQL</a></div>
        <div className="mt-1">Version:0.9</div>
      </footer>
      </body>
    </html>
  );
}
