import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        {children}
        <footer className="lg:ms-14">
        <div className="text-lg">By Jinwang Wu</div>
        <div className="text-lg">wujw2013@gmail.com</div>
      </footer>
      </body>
    </html>
  );
}
