name: Deploy Vehicle Dashboard App to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH key is loaded
        run: ssh-add -l  # Verify if the key was loaded successfully

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          # Add the server's public key to the known_hosts file
          ssh-keyscan -H 35.203.101.153 >> ~/.ssh/known_hosts
          # Ensure proper file permissions for the known_hosts file
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Test SSH connection with verbose output for debugging
          ssh -v root@35.203.101.153 << 'EOF'
            # Create the app directory if it doesn't exist
            [ ! -d "/app/react/vehicle-dashboard-react" ] && mkdir -p /app/react/vehicle-dashboard-react

            # Navigate to app directory or clone repo
            cd /app/react/vehicle-dashboard-react || git clone git@github.com:wujinwang/vehicle-dashboard-react.git .

            # Pull the latest changes
            git pull origin main

            # Install dependencies and build
            npm install
            npm run build

            # Restart NGINX (or your process manager)
            sudo systemctl restart nginx
          EOF
