name: Deploy React App to Linux Server

on:
  push:
    branches:
      - main  # Adjust the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            cd /path/to/your/app
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx  # Or restart your server or process manager
          EOF
