name: Deploy Vehicle Dashboard App to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: SSH_PRIVATE_KEY

      - name: Add server to known_hosts
        run: ssh-keyscan -H 35.203.101.153 >> ~/.ssh/github-actions

      - name: Deploy to server
        run: |
          ssh root@35.203.101.153 << 'EOF'
            # Create the app directory if it doesn't exist
            [ ! -d "/app/react/vehicle-dashboard-react" ] && mkdir -p /app/react/vehicle-dashboard-react

            # Navigate to app directory or clone repo
            cd /app/react/vehicle-dashboard-react || git clone git@github.com:wujinwang/vehicle-dashboard-react.git .

            # Pull the latest changes
            git pull origin main

            # Install dependencies and build
            npm install
            npm run build

            # Restart NGINX (or your process manager)
            sudo systemctl restart nginx
          EOF
